FROM registry.access.redhat.com/ubi9/ubi:9.8 AS llvm-build

WORKDIR /llvm

ARG max_jobs=8

RUN dnf -y update && \
    dnf install -y \
        git cmake ninja-build gcc gcc-c++ python3 python3-pip \
        make wget tar zlib-devel libxml2-devel openssl-devel && \
    dnf clean all

RUN git clone --depth 1 --branch llvmorg-19.1.0 https://github.com/llvm/llvm-project.git

WORKDIR /llvm/llvm-project/build

RUN cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="mlir;clang;lld" \
    -DLLVM_TARGETS_TO_BUILD="host" \
    -DLLVM_ENABLE_ASSERTIONS=OFF \
    -DLLVM_BUILD_TOOLS=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DCMAKE_INSTALL_PREFIX=/opt/llvm \
    ../llvm

RUN ninja -j"${max_jobs}" install